### ISSUE TITLE
Large boost circles overlapping numbers in vis

### ISSUE THREAD

**Issue by fabian-beck** [fabian-beck/pure-suggest#107]
![grafik](https://user-images.githubusercontent.com/5501795/159207326-db881327-0ff2-4a35-a036-b98ff01d68dd.png)

**Comment by cedrickrause** [comment]
What should we go for here, @fabian-beck? Moving it further to the top right?

**Comment by fabian-beck** [comment]
There are several opitions, not sure which one looks best:

1. Moving the circle further to the top right
2. Enlarging the box
3. Reducing the font size
4. Reducing the size of the circle(s)

Maybe a combination: (3) and (4)?
