### ISSUE TITLE
Correctly place "To be excluded"-overlays in the selected panel

### ISSUE THREAD

**Issue by SolRabs** [fabian-beck/pure-suggest#447]
In some cases, the "To be excluded"-overlay is shifted downwards, either appearing on publications that are not excluded or shifting into whitespace.

Recreation: Load example, add 5 more publications, mark bottom two publications to be excluded

Publications to be excluded:
![grafik](https://github.com/fabian-beck/pure-suggest/assets/124825505/978571a4-0627-4aeb-9446-020a0ad0af08)

Publication NOT to be excluded:
![grafik](https://github.com/fabian-beck/pure-suggest/assets/124825505/1551639e-639f-4831-a800-7686d3bc1067)

Overlay appearing in whitespace, if publication to be excluded is at the bottom of the list:
![grafik](https://github.com/fabian-beck/pure-suggest/assets/124825505/4815c114-48b0-4646-9c60-659098769bea)

**Comment by fabian-beck** [comment]
The overlays generally cause problems with z-order, so it might be better to replace them. See #476

**Comment by fabian-beck** [comment]
Should work now through implementing a simpler solution (#476).
