### ISSUE TITLE
Year labels in vis

### ISSUE THREAD

**Issue by fabian-beck** [fabian-beck/pure-suggest#48]

**Comment by cedrickrause** [comment]
Created breanch and pull request draft for this. Initial functionality is implemented. Needs further tuning though.

**Comment by fabian-beck** [comment]
Bug: labels still show and stack after clearing the session.

![grafik](https://user-images.githubusercontent.com/5501795/156918170-ebbc1f62-e8e1-4995-9ad8-287918e9f8c2.png)

**Comment by cedrickrause** [comment]
Bug is fixed now.
