### ISSUE TITLE
Author: undefined

### ISSUE THREAD

**Issue by xge** [fabian-beck/pure-suggest#58]
Try loading `10.1109/tvcg.2009.123` in PURE.
Authors actual: Ogawa and undefined
Authors expected: Ogawa and Ma

**Comment by fabian-beck** [comment]
Fixed: last name of second author is now shown in the short reference. 

However, the specific case also has a data issue, as first and last name are not split in "Kwan-Liu Ma" for this publication. Short reference is now "Ogawa and Kwan-Liu Ma, 2009".
