### ISSUE TITLE
Selecting multiple suggested publications at once

### ISSUE THREAD

**Issue by xge** [fabian-beck/pure-suggest#64]
Sometimes I find multiple interesting publications in the list of suggestions. Right now it's only possible to move one publication at a time from _suggested_ to _selected_. Doing so refreshes the list of suggested publications. The following re-ordering makes it hard to find the relevant publication again.

This could be fixed by allowing selection of multiple suggested publications at once.

**Comment by fabian-beck** [comment]
Very valid point. Solved by not immediately performing the update on suggestions, but queuing the publications for selection and let the user trigger the update when ready.
