### ISSUE TITLE
Discern selection-internal citation links from those connecting to suggested papers

### ISSUE THREAD

**Issue by fabian-beck** [fabian-beck/pure-suggest#95]
selection-internal links: continuous line
selection-to-suggestion: dashed line

**Comment by cedrickrause** [comment]
Implemented with [24c8145](https://github.com/fabian-beck/pure-suggest/commit/24c814524238cd22557db703b06e50c51806879c) . Dash pattern is currently set to "5 5" and can be adjusted in the style tag.

**Comment by fabian-beck** [comment]
Sorry, with the proposed styling, the selection-to-suggestion link caught too much attention because of the dashes. 

Flipped it now: made the selection-internal ones dashed (they are much fewer, and it is good if they catch attention). 

Considered in branch v0.1.2 for the respective next release.
